#define LINUX 0
#define WINDOWS 1
#define APPLE 0
#define MSVC 1
#define MINGW 0
#define CMAKE_MAKE_PROGRAM nmake
#define CMAKE_SYSTEM_NAME Windows
#define CMAKE_HOST_SYSTEM_NAME Windows //Windows, Linux or Darwin (OS X)
#define CMAKE_HOST_SYSTEM_PROCESSOR AMD64
#define CMAKE_CXX_COMPILER_VERSION 19.16.27026.1
#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 6
#define PROJECT_VERSION_PATCH 0
