name: Linux (GCC)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux_gcc:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        gccver: [ 9, 10, 11 ]
    steps:
      - name: Set up cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.21.x'

      - name: Set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.gccver }}
          platform: x64      - name: Install OpenGL and UDev
        run: sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libudev-dev
          submodules: recursive

      - name: Install SFML dependencies
        run: sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxcursor-dev libsfml-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev libxrandr-dev freeglut3-dev libjpeg-dev libfreetype6-dev libxrandr-dev libglew-dev libsndfile1-dev libopenal-dev libfreetype6-dev

      - name: Make build folder
        working-directory: ${{github.workspace}}
        run: mkdir build

      - name: CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -- -j4